USE master;
GO

ALTER DATABASE Ch10_Before SET OFFLINE WITH ROLLBACK IMMEDIATE;
ALTER DATABASE Ch10_Before SET ONLINE;
DROP DATABASE IF EXISTS Ch10_Before;

ALTER DATABASE Ch10_Normalized SET OFFLINE WITH ROLLBACK IMMEDIATE;
ALTER DATABASE Ch10_Normalized SET ONLINE;
DROP DATABASE IF EXISTS Ch10_Normalized;

